remote_theme: raviriley/agency-jekyll-theme

url    : "https://soulbondingtrip.com"

title      : Soul bonding trip
email      : info@soulbondingtrip.com
description: "Let's go on a soul bonding trip!"
author     : Skeeveecek
logo:     
  path: img\logo.jpg
  height: 60 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"

plugins:
  - jekyll-remote-theme
